//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hw7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ign
    {
        public double ID { get; set; }
        public string Title { get; set; }
        public string Platform { get; set; }
        public Nullable<double> Score { get; set; }
        public string Genre { get; set; }
        public Nullable<double> Year { get; set; }
        public Nullable<double> Month { get; set; }
        public Nullable<double> Day { get; set; }
    }
}
