//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hw7
{
    using System;
    using System.Collections.Generic;
    
    public partial class vg
    {
        public double ID { get; set; }
        public string Title { get; set; }
        public string Platform { get; set; }
        public double Year { get; set; }
        public string Genre { get; set; }
        public string Publisher { get; set; }
        public Nullable<double> NA_Sales { get; set; }
        public Nullable<double> EU_Sales { get; set; }
        public Nullable<double> JP_Sales { get; set; }
        public Nullable<double> Other_Sales { get; set; }
        public Nullable<double> Global_Sales { get; set; }
    }
}
